class DDMLogHelper{static logDownloadResult(resultData){if(DDMLogHelper._isLoggingEnabled()){var logMsg=`
                Eid: ${resultData.eid}
                ParsingStrategy: ${resultData.parsingStrategy || 'NA'}
                DownloadStatus: ${resultData.status}`;if(resultData.errorMessage){logMsg+=`\nErrorMessage: ${resultData.errorMessage}`;}
console.log(logMsg.split('\n').map(e=>e.trim()).join('\t').trim());console.log(resultData);}}
static logDownloadResultToServer(config,resultsData,origin){DDMLogHelper.logKeyEvent(resultsData,origin);const successCallback=(data)=>{if(DDMLogHelper._isLoggingEnabled()){console.log('Successfully logged download data to server.');}};const failureCallback=(xhr,status,error)=>{if(DDMLogHelper._isLoggingEnabled()){console.log('Error logging download data to server.');console.log(xhr);console.log(status);console.log(error);}};resultsData=DDMLogHelper._encodeResultsData(resultsData);var buckets=[];if(config.storeSuccessToS3||config.storeFailureToS3){resultsData.forEach(result=>{buckets.push([result]);});}else{buckets.push(resultsData);}
for(let index=0;index<buckets.length;index++){const results=buckets[index];jQuery.ajax({type:'POST',url:'/ddm/logdata.uri',data:{logData:JSON.stringify(results),origin:origin},success:successCallback,error:failureCallback});}}
static logKeyEvent(resultsData,origin){jQuery.ajax({type:'POST',url:'/ddm/logkeyevent.uri',data:{downloadCount:resultsData.length,origin:origin},success:function(data){if(DDMLogHelper._isLoggingEnabled()){console.log('Successfully logged key events.');}},error:function(xhr,status,error){if(DDMLogHelper._isLoggingEnabled()){console.log('Error logging key events.');console.log(xhr);console.log(status);console.log(error);}}});}
static logDebug(msg,data){if(DDMLogHelper._isLoggingEnabled()){if(data){console.log(msg,data);}else{console.log(msg);}}}
static _isLoggingEnabled(){return sessionStorage.getItem('ddmEnableLogging')==='true'||ScopusDDMEnableLogging;}
static _encodeResultsData(resultsData){var encodedResultsData=[];resultsData.forEach(result=>{result.pdfDownloadUrl=btoa(result.pdfDownloadUrl);result.publisherUrl=btoa(result.publisherUrl);result.license=btoa(result.license);encodedResultsData.push(result);});return encodedResultsData;}}
const DDM_EXTENSION_OPTIONS={retryCount:4,requestTimeout:60000};const DDM_EXTENSION_ACTION_NAMES={TEST_COMMUNICATION:'TestCommunication',GET_PDF_URL:'GetPDFUrl',GET_PDF:'GetPDF',DOWNLOAD_PDF:'DownloadPDF'};class DDMConfig{static loadConfig(){this._config={};DDMConfig._loadConfigFromScopus();DDMConfig._loadIgnorePublisherConfig();DDMConfig._loadExtensionConfig();return this._config;}
static getConfig(){return this._config;}
static _loadConfigFromScopus(){this._config=Object.assign(ScopusDDMConfig,this._config);}
static _loadIgnorePublisherConfig(){this._config=Object.assign({},this._config);}
static _loadExtensionConfig(){this._config=Object.assign({extensionOptions:DDM_EXTENSION_OPTIONS},this._config);}}
class DDMUtil{static getDomainUrl(url,protocol=true){var domainUrl='';if(typeof(url)!=='undefined'&&url!==''&&url.indexOf('://')>-1){domainUrl=url.split('/').slice(0,3).join('/');}
if(!protocol){return domainUrl.split('//')[1];}
return domainUrl;}
static isAbsoluteUrl(url){return(typeof(url)!=='undefined'&&url!==''&&url.indexOf('://')>-1);}
static getAbsoluteUrl(relativePath,hostUrl){var resultUrl='';if(!DDMUtil.isAbsoluteUrl(relativePath)){if(relativePath.trim()[0]==='/'){resultUrl=DDMUtil.getDomainUrl(hostUrl)+relativePath;}else{resultUrl=DDMUtil.getDomainUrl(hostUrl)+'/'+relativePath;}}else{resultUrl=relativePath||'';}
return resultUrl;}}
class DDMHelper{static userContentUniqueId(eid,userId){userId=userId+'';if(eid!=null&&eid!==''&&userId!==''){var eidNum=parseInt(eid.split('-').pop(0));var userIdNum=parseInt(userId.split(':').pop(0));return eidNum.toString(32)+'_'+userIdNum.toString(32);}else{return null;}}
static extractResultFromServiceResponse(serviceResponse){var responseData=serviceResponse.data;var result={parsingStrategy:'',errorMessage:'',license:'',publisherPageStatusCode:''};if(responseData.optionalData&&responseData.optionalData.loggingData){result.parsingStrategy=responseData.optionalData.loggingData.parsingStrategy||'';result.errorMessage=responseData.optionalData.loggingData.errorMessage||'';result.license=responseData.optionalData.loggingData.creativeLicense||'';result.publisherPageStatusCode=responseData.optionalData.loggingData.publisherResponseCode||'';}
if(responseData.pdfMetadata.success){result.status='success';if(responseData.action==='DownloadPDF'){result.pdfDownloadStatusCode=200;result.pdfDownloadStatusReason='pdf_download_success';}}else{result.status='failure';if(responseData.action==='DownloadPDF'){result.pdfDownloadStatusCode=400;result.pdfDownloadStatusReason='pdf_download_failure';}}
result.id=responseData.id;result.action=responseData.action;result.pdfLink=responseData.pdfMetadata.url;result.pluginVersion=serviceResponse.extensionVersion||'NA';return result;}
static generateResultData(config,browser,request,response){var resultData={browserName:browser.name,browserVersion:browser.version,pluginVersion:response.pluginVersion||'NA',pdfDownloadUrl:response.pdfLink||'',publisherUrl:request.publisherUrl||'',documentTitle:request.documentTitle,sourcecode:request.sourcecode,citationcode:request.citationcode,year:request.year,firstAuthor:(request.firstAuthor||'').trim(),journalName:(request.journalName||'').trim(),isOpenAccess:request.isOpenAccess,openAccessText:request.openAccessText,isGoldOA:request.isGoldOA,isSubscribed:request.isSubscribed,isGreenOA:request.isGreenOA,pdfLinkByOADOI:request.pdfLinkByOADOI,parsingStrategy:response.parsingStrategy||'NA',eid:request.eid,doi:request.doi,id:request.id,bestVersion:request.bestVersion,status:response.status,errorMessage:response.errorMessage||'',publisherPageStatusCode:response.publisherPageStatusCode||'NA',pdfDownloadStatusCode:response.pdfDownloadStatusCode||'NA',pdfDownloadStatusReason:response.pdfDownloadStatusReason||'NA',linkResolverAvailable:false,linkResolverUsed:'NA',linkResolverDownloadStatus:'NA',license:response.creativeLicense||'not found',contentId:request.contentId};if(response.responseHTML&&((config.storeSuccessToS3&&resultData.status==='success')||(config.storeFailureToS3&&resultData.status==='failure'))){resultData.responseHtml=btoa(unescape(encodeURIComponent(response.responseHTML)));}
return resultData;}}
class DDMExtensionServiceClient{static getExtensionStatus(){var elems=document.querySelectorAll('.DDMExtension-testelement');for(let index=0;index<elems.length;index++){var element=elems[index];element.remove();}
var requestEvent=new CustomEvent('DDMRequestEvent',{detail:{action:DDM_EXTENSION_ACTION_NAMES.TEST_COMMUNICATION}});document.dispatchEvent(requestEvent);var testElem=document.getElementById('DDMExtension-testelementid');return{installed:testElem?testElem.getAttribute('data-extension-loaded')==='true':false,enabled:testElem?testElem.getAttribute('data-extension-enabled')==='true':false};}
static getPdfUrl(config,request,origin){DDMExtensionServiceClient._submitEvent(config,request,origin,DDM_EXTENSION_ACTION_NAMES.GET_PDF_URL);}
static getPdf(config,request,origin){DDMExtensionServiceClient._submitEvent(config,request,origin,DDM_EXTENSION_ACTION_NAMES.GET_PDF);}
static downloadPdf(config,request,origin){DDMExtensionServiceClient._submitEvent(config,request,origin,DDM_EXTENSION_ACTION_NAMES.DOWNLOAD_PDF);}
static _submitEvent(config,request,origin,actionName){var fileNameFormat='';var eventDetail={id:request.id+'',action:actionName,options:{},articleMetadata:{},opaque:{uniqueId:request.doi,platformOrigin:origin}};eventDetail.options.loggingData=true;if(config.storeSuccessToS3||config.storeFailureToS3){eventDetail.options.publisherHTML=true;}
if(!request.filename){fileNameFormat=jQuery('input[name=fileFormatDDM]:checked').val()||'';if(config.useNameCriteria&&fileNameFormat){request.filename=DDMDownloadManager.generateFileName(request,fileNameFormat);}
else{request.filename=DDMDownloadManager.generateFileName(request,'1');}}
eventDetail.options.downloadFileName=request.filename;eventDetail.options.connectionTimeout=config.extensionOptions.requestTimeout;eventDetail.options.retryCount=config.extensionOptions.retryCount;eventDetail.articleMetadata.doi=request.doi;var requestEvent=new CustomEvent('DDMRequestEvent',{detail:eventDetail});document.dispatchEvent(requestEvent);}
static handleResponseEvent(event){var eventDetail=JSON.parse(event.detail);DDMExtensionServiceClient.sendResponse(eventDetail);}
static sendResponse(serviceResponse){var reqOrigin=serviceResponse.data.opaque.platformOrigin;if(reqOrigin===DDMBestVersionManager.name){DDMBestVersionManager.handleServiceClientResponse(serviceResponse);}else if(reqOrigin===DDMDownloadManager.name){DDMDownloadManager.handleServiceClientResponse(serviceResponse);}else{throw Error('Unable to respond to service request from unknown origin: '+reqOrigin);}}}
document.addEventListener('DDMResponseEvent',DDMExtensionServiceClient.handleResponseEvent);class DDMDownloadOptimizer{static persistResults(config,browser,resultsData,pageType){if(typeof ScopusDDMOptimizer.pageType==='undefined'){ScopusDDMOptimizer.pageType=pageType;ScopusDDMOptimizer.resultsData={};}
ScopusDDMOptimizer.resultsData[resultsData.id]=DDMDownloadOptimizer._cleanupResultToStore(resultsData);if(pageType==='recordpage'||(ScopusDDMGlobal.optimizedCount===ScopusDDMGlobal.totalDocs&&allSelectedEIDs.length===0)){DDMDownloadOptimizer.persistOptimizationStatus('complete');}else{DDMDownloadOptimizer.persistOptimizationStatus('in-progress');}}
static isOptimized(){return ScopusDDMOptimizer&&ScopusDDMOptimizer.status==='complete';}
static getOptimizedResults(id){return ScopusDDMOptimizer.resultsData?ScopusDDMOptimizer.resultsData[id]:{};}
static persistOptimizationStatus(status){ScopusDDMOptimizer.status=status;}
static storeRequestData(request){if(!ScopusDDMGlobal.requestData){ScopusDDMGlobal.requestData={};}
ScopusDDMGlobal.requestData[request.id]=request;}
static getRequestData(requestId){return ScopusDDMGlobal.requestData[requestId]||{};}
static _cleanupResultToStore(result){return result;}}
class DDMBestVersionManager{static determineBestVersion(docs,config,extensionStatus,displayType){var bestVerStrategy;if(config.isISSNEntitlementAvailable&&extensionStatus.installed&&extensionStatus.enabled){bestVerStrategy='Case#1';}else if(!config.isISSNEntitlementAvailable&&extensionStatus.installed&&extensionStatus.enabled){bestVerStrategy='Case#2';}else if(config.isISSNEntitlementAvailable&&!extensionStatus.installed&&!extensionStatus.enabled){bestVerStrategy='Case#3';}else if(!config.isISSNEntitlementAvailable&&!extensionStatus.installed&&!extensionStatus.enabled){bestVerStrategy='Case#4';}
ScopusDDMGlobal.optimizedCount=0;ScopusDDMGlobal.totalDocs=docs.length;for(const doc of docs){DDMBestVersionManager._applyBestVersionStrategy(bestVerStrategy,doc,config,displayType);}}
static _applyBestVersionStrategy(bestVerStrategy,doc,config,displayType){var determinePdfLink=false;var result={bestVersion:'',pdfLink:'',bestVerStrategy:bestVerStrategy,index:doc.index,id:doc.resultNum,doi:doc.doi,displayType:displayType,parsingStrategy:undefined};switch(bestVerStrategy){case'Case#1':result.bestVersion='Publisher';if(doc.isGoldOA){result.pdfLink=doc.pdfLinkByOADOI;}else if(doc.isSubscribed){determinePdfLink=true;}else{determinePdfLink=true;}
break;case'Case#2':result.bestVersion='Publisher';if(doc.isGoldOA){result.pdfLink=doc.pdfLinkByOADOI;}else{determinePdfLink=true;}
break;case'Case#3':result.bestVersion='Publisher';if(doc.isGoldOA){result.pdfLink=doc.pdfLinkByOADOI;}else if(doc.isSubscribed){}
break;case'Case#4':if(doc.isGoldOA){result.bestVersion='Publisher';result.pdfLink=doc.pdfLinkByOADOI;}else{result.bestVersion='VAP';result.pdfLink='';}
break;default:break;}
var request=Object.assign(doc,result);request.contentId=DDMHelper.userContentUniqueId(request.eid,config.webUserId);request.publisherUrl=doc.publisherUrl||'';DDMDownloadOptimizer.storeRequestData(request);var finalResult={id:request.id,parsingStrategy:'NA',pdfLink:''};if(request.pdfLink){DDMBestVersionManager.sendResponse(finalResult);}else if(!request.pdfLink&&!request.doi){finalResult.bestVersion='Abstract';finalResult.errorMessage='doi_not_found';finalResult.status='failure';DDMBestVersionManager.sendResponse(finalResult);}else if(determinePdfLink){if(displayType==='DOWNLOAD'){DDMExtensionServiceClient.downloadPdf(config,request,DDMBestVersionManager.name);}else{DDMExtensionServiceClient.getPdfUrl(config,request,DDMBestVersionManager.name);}}else{DDMBestVersionManager.sendResponse(finalResult);}}
static checkGreenOA(request,response){var result=Object.assign({},response);if(!response.pdfLink&&request.bestVerStrategy!=='Case#4'&&request.isGreenOA&&request.pdfLinkByOADOI){result.pdfLink=request.pdfLinkByOADOI;result.bestVersion='Repository';}else if(!request.doi){result.bestVersion='Abstract';result.errorMessage='doi_not_found';result.status='failure';}else if(!response.pdfLink){result.bestVersion='VAP';}
return result;}
static handleServiceClientResponse(serviceResponse){DDMBestVersionManager.sendResponse(DDMHelper.extractResultFromServiceResponse(serviceResponse));}
static sendResponse(response){var request=DDMDownloadOptimizer.getRequestData(response.id);var result=DDMBestVersionManager.checkGreenOA(request,response);var ignoreResponse=DDMIgnorePublisherManager.ignorePdfUrls(result,result.pdfLink);if(ignoreResponse){result=ignoreResponse;}
DDMDownloadManager.handleBestVersionResponse(request,result);}}
class DDMIgnorePublisherManager{static getIgnoreDomains(){if(typeof ScopusDDMGlobal.ignoreDomains==='undefined'){if(typeof ScopusDDMGlobal.ignoreDomainsString!=='undefined'){var domains=ScopusDDMGlobal.ignoreDomainsString.split(',').map(e=>e.trim()).filter(e=>e&&e!=='Enter_url_below');ScopusDDMGlobal.ignoreDomains=Array.from(new Set(domains));}else{ScopusDDMGlobal.ignoreDomains=[];}}
return ScopusDDMGlobal.ignoreDomains;}
static ignorePdfUrls(request,pdfLink){var ignoreResponse;if(pdfLink){var isMatch=DDMIgnorePublisherManager.getIgnoreDomains().some(function(item){return pdfLink.indexOf(item)>-1;});if(isMatch){ignoreResponse=Object.assign({},request);ignoreResponse.pdfLink='';ignoreResponse.errorMessage='publisher_in_ignore_list';ignoreResponse.status='failure';}}
return ignoreResponse;}}
class DDMDocumentsCollector{static getSelectionDetails(config,browser,pageType,isViewPdf,ajaxSource){var dataRow;var EIDs=[];var selCount=0;var selectedIndex=[];var resultsPerPage=0;var source;var tempRowId=-1;if(ajaxSource){source=jQuery(ajaxSource);resultsPerPage=selectedIndex.length;}
else{source=jQuery(document);resultsPerPage=Number.parseInt(source.find("#resultsPerPage").val()||'0');}
if(pageType==='recordpage'){selCount=1;selectedIndex=['1'];EIDs.push(source.find('#currentRecordPageEID').val());}else if(!getResultsDataHeader().isAllSelected()){if(isViewPdf||source.find('input[name=selectAllCheckBox]').is(':checked')){selectedIndex=source.find('input[name=selectedEIDs]').map((i,e)=>source.find('label[for="'+e.getAttribute('id')+'"]').closest('tr').attr('data-resultnum')).toArray();}else{selectedIndex=source.find('input[name=selectedEIDs]:checked').map((i,e)=>source.find('label[for="'+e.getAttribute('id')+'"]').closest('tr').attr('data-resultnum')).toArray();}
selCount=selectedIndex.length;selectedIndex=selectedIndex.map(e=>Number.parseInt(e));selectedIndex.forEach((resultNum,ind)=>{if(ajaxSource){tempRowId=tempRowId+1;}
else{tempRowId=resultNum-1;tempRowId=tempRowId%resultsPerPage;}
dataRow=source.find('#resultDataRow'+tempRowId);EIDs.push(dataRow.find('input[name=selectedEIDs]').val());});}
return{count:selCount,selectedIndex:selectedIndex,EIDs:EIDs};}
static collectPageDocuments(config,browser,selectedIndex,pageType,displayType,ajaxSource){var authors='';var docs=[];var dataRow;var firstAuthor="";var indexPrefix="";var isOptimized;var linksRow;var resultsIndex;var resultsPerPage;var source;var tempRowId;if(ajaxSource){source=jQuery(ajaxSource);indexPrefix="a";}
else{source=jQuery(document);if(displayType==='DOWNLOAD'){indexPrefix="p";}}
isOptimized=DDMDownloadOptimizer.isOptimized();if(displayType==='DOWNLOAD'&&isOptimized){selectedIndex.forEach((resultNum)=>{docs.push(DDMDownloadOptimizer.getOptimizedResults(resultNum));});return docs;}
if(pageType==='recordpage'){if((source.find('#authorlist li a')||[{}])[0]){firstAuthor=(source.find('#authorlist li a')||[{}])[0].text;}
docs.push(DDMDocumentsCollector._generateDocumentData(config,browser,{index:1,resultNum:indexPrefix+"1",doi:source.find('meta[name="dc.identifier"]').attr('content'),eid:source.find('#currentRecordPageEID').val(),sourcecode:source.find('#sourceType').val(),citationcode:source.find('#citationType').val(),documentTitle:source.find('#profileleftinside h2[class=h3]').contents().not(jQuery("#profileleftinside h2[class=h3]").children()).add(jQuery("#profileleftinside h2[class=h3] .ScopusTermHighlight")).text().trim(),journalName:source.find('#publicationTitle').text(),year:source.find('#publicationYear').val(),firstAuthor:firstAuthor,isOpenAccess:source.find('#articleTitleInfo #openAccessNotice').length>0,openAccessText:source.find('#articleTitleInfo #openAccessNotice').text().trim()}));if(displayType==='VIEW_PDF'){source.find('#viewPdfButtonDiv').append(source.find('#ddmViewPdfButtonTemplate .viewPdfButton').clone());}}else{if(getResultsDataHeader().isAllSelected()){resultsPerPage=config.maxDownload;resultsIndex=new Array(0);for(var counter=0;counter<resultsPerPage;counter=counter+1){resultsIndex.push(counter+1);}}
else{if(ajaxSource){resultsPerPage=selectedIndex.length;}
else{resultsPerPage=Number.parseInt(source.find("#resultsPerPage").val()||'0');}
resultsIndex=selectedIndex;}
resultsIndex.forEach((resultNum,ind)=>{tempRowId=resultNum-1;tempRowId=tempRowId%resultsPerPage;dataRow=source.find('#resultDataRow'+tempRowId);if(dataRow.find('input[name=selectedEIDs]').val()!==undefined){linksRow=source.find('#resultLinkRow'+tempRowId);authors=dataRow.find('td[data-type="authors"] a');docs.push(DDMDocumentsCollector._generateDocumentData(config,browser,{index:ind+1,resultNum:indexPrefix+Number.parseInt(resultNum),doi:dataRow.find('div[class=checkbox]').attr('data-doi'),eid:dataRow.find('input[name=selectedEIDs]').val(),sourcecode:linksRow.attr('data-sourcecode'),citationcode:linksRow.attr('data-citationcode'),documentTitle:dataRow.find('td[data-type="docTitle"] a').text(),journalName:dataRow.find('td[data-type="source"] #sourceTitle').text(),year:dataRow.find('td[data-type="year"]').text(),firstAuthor:authors.length?authors[0].text:'',isOpenAccess:dataRow.find('.openAccessTxt').length>0,openAccessText:dataRow.find('.openAccessTxt').text().trim(),}));if(displayType==='VIEW_PDF'){var btn=jQuery('<li>').append(jQuery('#ddmViewPdfButtonTemplate .viewPdfButton').outerHTML());btn.insertBefore(jQuery('#resultLinkRow'+tempRowId+' ul li a[id*="resultRelatedLink"]').closest('li'));}}});}
return docs;}
static _generateDocumentData(config,browser,data){var doc={index:data.index,resultNum:data.resultNum,id:data.resultNum,doi:data.doi,eid:data.eid,sourcecode:data.sourcecode,citationcode:data.citationcode,documentTitle:(data.documentTitle||'').trim(),year:(data.year||'').trim(),firstAuthor:(data.firstAuthor||'').trim(),journalName:(data.journalName||'').trim(),isOpenAccess:data.isOpenAccess,openAccessText:data.openAccessText,isGoldOA:false,isSubscribed:true,isGreenOA:false,pdfLinkByOADOI:'',pdfLink:'',publisherUrl:config.doiBaseUrl+data.doi};return doc;}
static retrieveSelectedEids(config){var ajaxDocs;var resultsPage;var selection;var urlString=window.location.href+"&DDMDownload=true";if(getResultsDataHeader().isAllSelected()){urlString=urlString+"&selectAllCheckBox=true"}
else{urlString=urlString+"&selectAllCheckBox=false"}
jQuery.ajax({url:urlString,type:"GET",dataType:"HTML",async:false,success:function(response){resultsPage=response;},error:function(error){resultsPage="";}});selection=DDMDocumentsCollector.getSelectionDetails(this.config,this.browser,this.pageType,true,resultsPage);ajaxDocs=DDMDocumentsCollector.collectPageDocuments(config,"",selection.selectedIndex,"","DOWNLOAD",resultsPage);return ajaxDocs;}
static getUnSelectedEIDs(allSelectedEIDs){var curEID;var dataRow;var deselectEIDs=[];var eidChecked;var eidFound;var eidRowIndex=jQuery(document).find('input[name=selectedEIDs]').map((i,e)=>jQuery(document).find('label[for="'+e.getAttribute('id')+'"]').closest('tr').attr('data-resultnum')).toArray();var tempRowId;for(tempRowId in eidRowIndex){dataRow=jQuery(document).find('#resultDataRow'+tempRowId);if(dataRow){curEID=dataRow.find('input[name=selectedEIDs]').val();eidChecked=dataRow.find('input[name=selectedEIDs]').attr("checked");eidFound=false;if($.inArray(curEID,allSelectedEIDs)>-1){eidFound=true;}
if(eidFound&&!eidChecked){deselectEIDs.push(curEID);}}}
return deselectEIDs;}
static getExtraSelectedResults(config,docs,selection){var ajaxDocs;var currentDoc;var deselectedEIDs=[];var docCount;var docsExceeded=false;$('#DDMDownload').val("true");var ajaxCallWouldFindDocuments=(getResultsDataHeader().getOffPageSelectionCount()>0);var roomAvailableInBoat=(selection.EIDs.length<config.maxDownload);if(ajaxCallWouldFindDocuments&&roomAvailableInBoat){ajaxDocs=DDMDocumentsCollector.retrieveSelectedEids(config);deselectedEIDs=DDMDocumentsCollector.getUnSelectedEIDs(allSelectedEIDs);docCount=docs.length;for(currentDoc in ajaxDocs){if((!selection.EIDs.includes(ajaxDocs[currentDoc].eid))&&(!deselectedEIDs.includes(ajaxDocs[currentDoc].eid))){docCount=docCount+1;if(docCount<=config.maxDownload){docs.push(ajaxDocs[currentDoc]);}
else{docsExceeded=true;}}}
if((getResultsDataHeader().isAllSelected())&&(docs.length===config.maxDownload)){docsExceeded=true;}
if(((allSelectedEIDs.length-deselectedEIDs.length+selection.count)>config.maxDownload)&&(docs.length===config.maxDownload)){docsExceeded=true;}}
if(((allSelectedEIDs.length-deselectedEIDs.length)>0)&&(selection.EIDs.length===config.maxDownload)&&(allSelectedEIDs.filter(function(value){return selection.EIDs.indexOf(value)===-1;}).length>0)){docsExceeded=true;}
return{docs:docs,docsExceeded:docsExceeded};}}
class DDMDownloadManager{constructor(){this.additionalSel={};this.browser=getBrowserInfo();this.config=DDMConfig.loadConfig();this.extensionStatus=DDMExtensionServiceClient.getExtensionStatus();this.pageType=DDMDownloadManager.getPageType();this.messageHelper=new DDMExtensionScopusMsgHelper(this.browser,this.config,this.extensionStatus);this.selection={};this.fileNameFormat='';this.docsExceeded=false;}
initiateBestVersion(){if(this.config.isViewPdfEnabled){this.selection=DDMDocumentsCollector.getSelectionDetails(this.config,this.browser,this.pageType,true,null);this.bestDocs=DDMDocumentsCollector.collectPageDocuments(this.config,this.browser,this.selection.selectedIndex,this.pageType,'VIEW_PDF',null);DDMBestVersionManager.determineBestVersion(this.bestDocs,this.config,this.extensionStatus,'VIEW_PDF');}}
initiateDownload(){var canProceed=this.messageHelper.canProceedDownload();var totalCount=0;if(canProceed){this.selection=DDMDocumentsCollector.getSelectionDetails(this.config,this.browser,this.pageType,false,null);totalCount=this.selection.count;if(totalCount>this.config.maxDownload){canProceed=confirm(this.config.maxDownloadMsg);if(canProceed){this.selection.count=this.config.maxDownload;this.selection.selectedIndex=this.selection.selectedIndex.slice(0,this.config.maxDownload);}}}
if(canProceed){this.drawDownloadModal(canProceed);if((this.pageType==='recordpage')&&(!ScopusDDMConfig.useNameCriteria)){jQuery('#btnDDMDownloadStart').click();}}}
drawDownloadModal(canProceed){var extraResults;if((typeof ResultsDataHeader!=='undefined')&&((ResultsDataHeader.getOffPageSelectionCount()>0)&&ResultsDataHeader.isAllSelected())){this.docs=[];}else{this.docs=DDMDocumentsCollector.collectPageDocuments(this.config,this.browser,this.selection.selectedIndex,this.pageType,'DOWNLOAD',null);}
if(this.pageType!='recordpage'){extraResults=DDMDocumentsCollector.getExtraSelectedResults(this.config,this.docs,this.selection);this.docs=extraResults.docs;this.docsExceeded=extraResults.docsExceeded;}
if(this.docsExceeded){canProceed=confirm(this.config.maxDownloadMsg);}
if(canProceed){var tbody=jQuery('#ddmDownloadModal #tableBody');tbody.html('');jQuery('#ddmModalMsgArea').attr('class','alert alert-info noMargin');jQuery('#ddmModalMsgArea p#ddmDownloadMsg').html(this.config.downloadInfoMsg);jQuery('#btnDDMDownloadStart').removeAttr('disabled');jQuery('#btnDDMDownloadStart').removeClass('hidden');jQuery('#btnDDMDownloadComplete').addClass('hidden');jQuery('#ddmDownloadModal').unbind();jQuery('#ddmDownloadModal').removeClass('hidden');jQuery('#ddmDownloadModal').modal({backdrop:'static'});var tbody=jQuery('#ddmDownloadModal #tableBody');var tr,td;this.docs.forEach((doc,ind)=>{tr=jQuery('<tr>',{'data-eid':doc.eid,'data-sourcecode':doc.sourcecode,'data-citationcode':doc.citationcode});td=jQuery('<th>',{'scope':'row','class':'noPadding marginTopHalf marginBottomHalf'});td.append(jQuery('<label>',{'text':(ind+1)+'.'}));tr.append(td);td=jQuery('<td>',{'text':doc.documentTitle,'class':'paddingLeftHalf noPaddingTop marginTopHalf marginBottomHalf'});if(doc.isOpenAccess){td.append(jQuery('<span>',{'text':doc.openAccessText,'class':'openAccessTxt paddingLeftQuarter'}));}
tr.append(td);td=jQuery('<td>',{'id':'status-'+doc.id,'class':'noPaddingTop noPaddingBottom downloadStatus marginTopHalf marginBottomHalf paddingRight1 textRight'});tr.append(td);tbody.append(tr);});}}
processDownload(){this.fileNameFormat=jQuery('input[name=fileFormatDDM]:checked').val()||'';ScopusDDMGlobal.downloadCompleteCount=0;ScopusDDMGlobal.downloadSuccessCount=0;ScopusDDMGlobal.downloadTotalCount=this.docs.length;if(DDMDownloadOptimizer.isOptimized()){this.docs.forEach((doc)=>{if(doc.pdfDownloadUrl&&doc.status==='success'){this.processDownloadItem(doc);}else{this.displayDownloadStatus(doc);}});}else{DDMBestVersionManager.determineBestVersion(this.docs,this.config,this.extensionStatus,'DOWNLOAD');}}
processDownloadItem(request){request.url=request.pdfDownloadUrl;if(this.config.useNameCriteria&&this.fileNameFormat){request.filename=DDMDownloadManager.generateFileName(request,this.fileNameFormat);}
else{request.filename=DDMDownloadManager.generateFileName(request,'1');}
DDMDownloadOptimizer.storeRequestData(request);DDMExtensionServiceClient.downloadPdf(this.config,request,DDMDownloadManager.name);}
static generateFileName(doc,fileNameFormat){var filename='';switch(fileNameFormat){case'1':filename=[doc.documentTitle,doc.year,doc.journalName].join('_');break;case'2':filename=[doc.firstAuthor,doc.documentTitle,doc.year].join('_');break;case'3':filename=doc.doi;break;}
filename=filename.trim().replace(/[^a-zA-Z0-9 ]/g,'').replace(/ /g,'-')+'.pdf';if(filename.length>255){filename=filename.substring(0,251)+'.pdf';}
return filename;}
downloadStart(){jQuery('#ddmDownloadModal #tableBody .downloadStatus').append(jQuery('#ddmLoadingIconTemplate span.loading-wrapper').clone());jQuery('#btnDDMDownloadStart').attr('disabled','disabled');}
downloadComplete(totalCount,successCount){jQuery('#btnDDMDownloadStart').addClass('hidden');jQuery('#btnDDMDownloadComplete').removeClass('hidden');if(successCount===0&&totalCount===1){jQuery('#ddmModalMsgArea').attr('class','alert alert-danger noMargin');jQuery('#ddmModalMsgArea p#ddmDownloadMsg').html(this.config.downloadErrorMsgSingle);}else if(successCount===0&&totalCount>1){jQuery('#ddmModalMsgArea').attr('class','alert alert-danger noMargin');jQuery('#ddmModalMsgArea p#ddmDownloadMsg').html(this.config.downloadErrorMsgMultiple);}else if(successCount===1){jQuery('#ddmModalMsgArea').attr('class','alert alert-success noMargin');jQuery('#ddmModalMsgArea p#ddmDownloadMsg').html(successCount+' '+this.config.downloadSuccessMsgSingle);}else{jQuery('#ddmModalMsgArea').attr('class','alert alert-success noMargin');jQuery('#ddmModalMsgArea p#ddmDownloadMsg').html(successCount+' '+this.config.downloadSuccessMsgMultiple);}}
displayDownloadStatus(resultData){ScopusDDMGlobal.downloadCompleteCount+=1;if(resultData.status==='success'){ScopusDDMGlobal.downloadSuccessCount+=1;}
var statusElem=jQuery('#ddmDownloadModal #tableBody #status-'+resultData.id);statusElem.find('.loading-wrapper').remove();var cloneTemp;if(resultData.status==='success'){statusElem.append(jQuery('#ddmDownloadStatusTemplate #ddmDownloadedStatus').clone());}else if(resultData.bestVersion==='Abstract'||resultData.errorMessage==='doi_not_found'){cloneTemp=jQuery('#ddmDownloadStatusTemplate #ddmAbstractStatus').clone();cloneTemp.find('a').attr('href',`${this.config.recordPageBaseUrl}?eid=${resultData.eid}&origin=resultslist`);statusElem.append(cloneTemp);}else if(resultData.status==='error'){resultData.pdfDownloadStatusCode=400;resultData.pdfDownloadStatusReason='pdf_download_failed';statusElem.append(jQuery('#ddmDownloadStatusTemplate #ddmErrorStatus').clone());}else{cloneTemp=jQuery('#ddmDownloadStatusTemplate #ddmVAPStatus').clone();cloneTemp.find('a').attr('href',resultData.publisherUrl);statusElem.append(cloneTemp);}
DDMLogHelper.logDownloadResult(resultData);if(!ScopusDDMGlobal.downloadData){ScopusDDMGlobal.downloadData={};}
ScopusDDMGlobal.downloadData[resultData.id]=resultData;if(ScopusDDMGlobal.downloadTotalCount==ScopusDDMGlobal.downloadCompleteCount){this.downloadComplete(ScopusDDMGlobal.downloadTotalCount,ScopusDDMGlobal.downloadSuccessCount);DDMLogHelper.logDownloadResultToServer(this.config,Object.values(ScopusDDMGlobal.downloadData),this.pageType);delete ScopusDDMGlobal.downloadData;}}
displayViewPdfButton(result){var viewPdfElem;var btnText;if(this.pageType==='recordpage'){viewPdfElem=jQuery('#viewPdfButtonDiv .viewPdfButton');viewPdfElem.addClass('pull-right');}else{viewPdfElem=jQuery('tr[id*="resultLinkRow"][data-resultnum='+result.id+'] ul .viewPdfButton');}
viewPdfElem.attr('data-parsingStrategy',result.parsingStrategy);btnText=viewPdfElem.find('.btnText');var hideViewPdf=false;if(result.bestVersion==='Abstract'){hideViewPdf=true;viewPdfElem.attr('onclick',`window.open("${this.config.recordPageBaseUrl}?eid=${result.eid}&origin=resultslist");`);}else if(result.status==='success'&&(result.bestVersion==='Publisher'||result.bestVersion==='Repository')){btnText.html('View PDF');viewPdfElem.prepend('<span class="resultsPageIcons pdfDocumentIcon" aria-hidden="true"></span>');viewPdfElem.attr('onclick',`window.open("${result.pdfDownloadUrl}");`);}else{btnText.html('View at publisher');hideViewPdf=true;viewPdfElem.attr('onclick',`window.open("${result.publisherUrl}");`);}
if(hideViewPdf){if(this.pageType==='recordpage'){viewPdfElem.addClass('hidden');}else{viewPdfElem.closest('li').addClass('hidden');}}
viewPdfElem.find('.loading-wrapper').remove();}
getMessageHelper(){return this.messageHelper;}
static handleBestVersionResponse(request,response){var downloadManager=getDownloadManager();ScopusDDMGlobal.optimizedCount+=1;var resultData=DDMHelper.generateResultData(downloadManager.config,downloadManager.browser,request,response);if(request.displayType==='VIEW_PDF'){downloadManager.displayViewPdfButton(resultData);var pageType=DDMDownloadManager.getPageType();if((pageType==='resultspage'&&jQuery('#resultsListToolbar .docHeaderLinks.lnkDisabled').length)||pageType==='recordpage'){DDMDownloadOptimizer.persistResults(downloadManager.config,downloadManager.browser,resultData,pageType);}}else if(request.displayType==='DOWNLOAD'){downloadManager.displayDownloadStatus(resultData);}}
static handleServiceClientResponse(serviceResponse){var downloadManager=getDownloadManager();var resultData=DDMHelper.generateResultData(downloadManager.config,downloadManager.browser,DDMDownloadOptimizer.getRequestData(serviceResponse.data.id),DDMHelper.extractResultFromServiceResponse(serviceResponse));downloadManager.displayDownloadStatus(resultData);}
static getPageType(){if(window.location.href.indexOf('record/display.uri')>-1){return'recordpage';}
return'resultspage';}}
class DDMExtensionScopusMsgHelper{constructor(browser,config,extensionStatus){this.extensionStatus=extensionStatus;this.browser=browser;this.config=config;}
canProceedDownload(){var proceed=false;if(!this.browser||!this.browser.name||!this.browser.version){throw Error('Browser not idenfitied');}
if(this.browser.name==='Chrome'){proceed=this.checkForExtensionInstallation(this.config.installMsg.chrome);}else if(this.browser.name==='Firefox'){proceed=this.checkForExtensionInstallation(this.config.installMsg.firefox);}else{proceed=this.showNotSupportedMessage();}
return proceed;}
checkForExtensionInstallation(brwoserSpecificMsg){if(!this.extensionStatus.installed){this.showGetExtensionMessage(brwoserSpecificMsg);return false;}
if(this.extensionStatus.installed&&!this.extensionStatus.enabled){this.showRefreshErrorMessage();return false;}
return true;}
showNotSupportedMessage(){jQuery('#ddmBrowserNotSupportedModal').removeClass('hidden');jQuery('#ddmBrowserNotSupportedModal').modal({backdrop:'static'});return false;}
showGetExtensionMessage(brwoserSpecificMsg){jQuery('#ddmGetExtensionModal .modal-body').html(brwoserSpecificMsg);jQuery('#ddmGetExtensionModal').removeClass('hidden');jQuery('#ddmGetExtensionModal').modal({backdrop:'static'});return false;}
showRefreshMessage(){window.open(this.config.extensionURL[this.browser.name.toLowerCase()]);jQuery('#ddmWelcomeBackModal').removeClass('hidden');jQuery('#ddmWelcomeBackModal').modal({backdrop:'static'});return false;}
showRefreshErrorMessage(){jQuery('#ddmErrorModal').removeClass('hidden');jQuery('#ddmErrorModal').modal({backdrop:'static'});return false;}}
function getDownloadManager(){if(!ScopusDDMGlobal.mgr){ScopusDDMGlobal.mgr=new DDMDownloadManager();}
return ScopusDDMGlobal.mgr;}
function getDDMExtensionReloadResults(form,page){sessionStorage.setItem('ddmDownloadInitiated',true);jQuery(form).children("input[name='searchWithinResultsDefault']").val('f');jQuery(form).children("input[name='news']").val('');jQuery(form).children("input[name='documentJumpToPageDefault']").val('t');if(jQuery(form).children("input[name='details']")){jQuery(form).children("input[name='details']").val('');}
jQuery("input[name='currentPage']").val(page);var go=jQuery("<input>").attr({'type':'hidden','name':'go','value':'GO'});jQuery("input[name='clickedLink']").val('go');jQuery(form).append(go);jQuery(form).attr('target','_self');jQuery(form).submit();}
function getDDMExtensionReloadDocument(){sessionStorage.setItem('ddmDownloadInitiated',true);window.location.reload();}
function enableDDMLogging(){sessionStorage.setItem('ddmEnableLogging',true);}
jQuery(document).ready(function(){jQuery('#ddmDownloadButton').on('click',function(e){getDownloadManager().initiateDownload();});jQuery('#btnDDMDownloadStart').on('click',function(e){getDownloadManager().downloadStart();getDownloadManager().processDownload();});jQuery('#btnGetExtension,#btnGetExtensionOnRefresh').on('click',function(e){getDownloadManager().getMessageHelper().showRefreshMessage();});if(sessionStorage.getItem('ddmDownloadInitiated')){sessionStorage.removeItem('ddmDownloadInitiated');getDownloadManager().initiateDownload();}
getDownloadManager().initiateBestVersion();});